store:
    availabilities:
        - German
        - International
    default_locale: de_DE
    localizations:
        - de_DE
        - en_GB
    categories:
        - loyalityAndRewards
    type: extension
    icon: src/Resources/store/icon.png
    automatic_bugfix_version_compatibility: true
    description:
        de: '<b>Shopping App für Shopware 6&nbsp;</b><br><a href="https://www.shopgate.com/demo-buchen" target="_blank" rel="noreferrer noopener">Jetzt Demo anfordern</a><b><a href="http://www.shopgate.com/de/shopware/?ref=shopware_store"></a></b><br><br><p>Eine eigene Shopping App hilft Händler*innen, bei Kunden*innen dauerhaft präsent zu bleiben. Zudem bieten Sie wiederkehrenden Kunden*innen mit einer mobilen App die schnellste, einfachste und bequemste Möglichkeit online zu bestellen.</p><p>Darüber hinaus bietet Ihnen eine eigene App die Möglichkeit über Push-Nachrichten, Loyality-Systeme und digitale Kundenkarten ganz neue Marketing-Kanäle zu öffnen und so langfristige Kundenbindung zu erzielen.</p><p>Kurz: Apps gehören heute zu den stärksten digitalen Instrumenten, um Kunden*innen an Ihr Unternehmen zu binden und Angebote bei bestehenden Kunden*innen zu vermarkten.</p><p>Shopgate hat eine Plattform entwickelt, um hoch performante, individualisierte Shopping Apps zu bauen, zu veröffentlichen und für Händler*innen auf dem neusten Stand zu halten – für einen Bruchteil des Preises, den Sie für eine Eigenentwicklung investieren müssten.</p><br>Kontakt:&nbsp;<p>Telefon: +49 6033 74700&nbsp;</p><p>E-Mail: sales-de@shopgate.com &nbsp;</p><p><a href="https://account.shopware.com/www.shopgate.com%C2%A0">www.shopgate.com&nbsp;</a></p>'
        en: '<b>Shopping App for Shopware&nbsp;</b><br><br><p>Having your own shopping app helps merchants to maintain a lasting presence among customers. In addition, with a mobile app you offer returning customers the fastest, easiest and most convenient way to order online.</p><p><br></p><p>In addition, your own app offers you the opportunity to open up completely new marketing channels via push messages, loyalty systems and digital customer cards and thus achieve long-term customer loyalty.</p><p><br></p><p>In short, apps are one of today''s most powerful digital tools for building customer loyalty and marketing offers to existing customers.</p><p><br></p><p>Shopgate has developed a platform to build and publish high-performance, individualized shopping apps and keep them up-to-date for merchants - for a fraction of the price you would have to invest for an in-house development.</p><p><br></p><p>Contact:&nbsp;</p><p>Phone: +49 6033 74700&nbsp;</p><p>E-mail: sales@shopgate.com&nbsp;&nbsp;</p>'
    installation_manual:
        de: <p>Mit dem Einrichten der Shopgate-App, können Sie von einer Reihe von Features profitieren, die unmittelbar in Ihren mobilen Shop und die Apps übernommen werden:&nbsp;<a href="https://support.shopgate.com/hc/de/articles/202798446-Anbindung-an-Shopware%C2%A0">https://support.shopgate.com/hc/de/articles/360021478860-Shopware-6</a></p>
        en: <ul><li>Please check here how to easily connect with Shopgate: <a href="https://support.shopgate.com/hc/de/articles/360021478860-Shopware-6">https://support.shopgate.com/hc/de/articles/360021478860-Shopware-6</a></li></ul>
    tags:
        de:
            - App
            - Mobile App
            - Native App
            - Mobile Commerce
        en:
            - App
            - Mobile App
            - Native App
            - shopping app
    videos:
        de: []
        en: []
    highlights:
        de:
            - Schnellere Time-to-Market durch Software-as-a-Service
            - Individuell anpassbar durch Ihre Entwickler
            - Support und App-Management inklusive
            - Wartung und Hosting inklusive
        en:
            - Faster time-to-market through Software-as-a-Service
            - Customizable by your developers
            - Support and app management included
            - Maintenance and hosting included
    features:
        de:
            - Native App für iPhone und Android Smartphones
            - Unlimitierte Push-Nachrichten inklusive
            - Individuell anpassbare App-Technologie
            - Schnittstellen zu über 50 Technologie-Partnern
            - Drag & Drop CMS-System
            - Backend & Analytics
        en:
            - Native app for iPhone and Android smartphones
            - Unlimited push messages included
            - Customizable app technology
            - Interfaces to over 50 technology partners
            - Drag & Drop CMS system
            - Backend & Analytics
    faq:
        de: []
        en: []
    images:
        - file: src/Resources/store/img-0.png
          activate:
            de: true
            en: false
          preview:
            de: false
            en: false
          priority: 20
        - file: src/Resources/store/img-1.png
          activate:
            de: false
            en: true
          preview:
            de: false
            en: false
          priority: 21
        - file: src/Resources/store/img-2.png
          activate:
            de: true
            en: true
          preview:
            de: true
            en: true
          priority: 0
        - file: src/Resources/store/img-3.png
          activate:
            de: true
            en: false
          preview:
            de: false
            en: false
          priority: 0
        - file: src/Resources/store/img-4.png
          activate:
            de: false
            en: true
          preview:
            de: false
            en: false
          priority: 0
        - file: src/Resources/store/img-5.png
          activate:
            de: true
            en: true
          preview:
            de: false
            en: false
          priority: 0
        - file: src/Resources/store/img-6.png
          activate:
            de: true
            en: false
          preview:
            de: false
            en: false
          priority: 0
        - file: src/Resources/store/img-7.png
          activate:
            de: true
            en: true
          preview:
            de: false
            en: false
          priority: 0
build:
    extraBundles: []
    zip:
        composer:
            enabled: true
            before_hooks: []
            after_hooks: []
            excluded_packages:
              - shopware/core
              - symfony/expression-language
        assets:
            enabled: false
            before_hooks: []
            after_hooks: []
            enable_es_build_for_admin: false
            enable_es_build_for_storefront: false
        pack:
            excludes:
                paths:
                  - phpunit.xml.dist
                  - composer.lock
            before_hooks: []
